name: "Docker"

on:
  workflow_dispatch:

  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/adminerevo"
        tag: "${{ matrix.item }}"
        context: "${{ matrix.context }}"
    strategy:
      matrix:
        include:
          - { item: latest, context: adminerevo }

      fail-fast: false
